apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: e-commerce-web
data:
  JWT_SECRET: your_jwt_secret
  # Naye user credentials ka use karein
  MONGODB_URI: mongodb://ecommerce_user:ecommerce_password@mongo:27017/ecommerce_forever # <-- Naye user/passwords se badlein
